// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumSample int32

const (
	EnumSample_UNKNOWN EnumSample = 0
	EnumSample_STARTED EnumSample = 1
	EnumSample_RUNNING EnumSample = 1
)

var EnumSample_name = map[int32]string{
	0: "UNKNOWN",
	1: "STARTED",
	// Duplicate value: 1: "RUNNING",
}

var EnumSample_value = map[string]int32{
	"UNKNOWN": 0,
	"STARTED": 1,
	"RUNNING": 1,
}

func (x EnumSample) String() string {
	return proto.EnumName(EnumSample_name, int32(x))
}

func (EnumSample) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

type Book struct {
	Isbn                 int64    `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetIsbn() int64 {
	if m != nil {
		return m.Isbn
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type GetBookRequest struct {
	Isbn                 int64    `protobuf:"varint,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetIsbn() int64 {
	if m != nil {
		return m.Isbn
	}
	return 0
}

type GetBookViaAuthor struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookViaAuthor) Reset()         { *m = GetBookViaAuthor{} }
func (m *GetBookViaAuthor) String() string { return proto.CompactTextString(m) }
func (*GetBookViaAuthor) ProtoMessage()    {}
func (*GetBookViaAuthor) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *GetBookViaAuthor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookViaAuthor.Unmarshal(m, b)
}
func (m *GetBookViaAuthor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookViaAuthor.Marshal(b, m, deterministic)
}
func (m *GetBookViaAuthor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookViaAuthor.Merge(m, src)
}
func (m *GetBookViaAuthor) XXX_Size() int {
	return xxx_messageInfo_GetBookViaAuthor.Size(m)
}
func (m *GetBookViaAuthor) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookViaAuthor.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookViaAuthor proto.InternalMessageInfo

func (m *GetBookViaAuthor) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type BookStore struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Books                map[int64]string `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BookStore) Reset()         { *m = BookStore{} }
func (m *BookStore) String() string { return proto.CompactTextString(m) }
func (*BookStore) ProtoMessage()    {}
func (*BookStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *BookStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookStore.Unmarshal(m, b)
}
func (m *BookStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookStore.Marshal(b, m, deterministic)
}
func (m *BookStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookStore.Merge(m, src)
}
func (m *BookStore) XXX_Size() int {
	return xxx_messageInfo_BookStore.Size(m)
}
func (m *BookStore) XXX_DiscardUnknown() {
	xxx_messageInfo_BookStore.DiscardUnknown(m)
}

var xxx_messageInfo_BookStore proto.InternalMessageInfo

func (m *BookStore) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BookStore) GetBooks() map[int64]string {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterEnum("example.EnumSample", EnumSample_name, EnumSample_value)
	proto.RegisterType((*Book)(nil), "example.Book")
	proto.RegisterType((*GetBookRequest)(nil), "example.GetBookRequest")
	proto.RegisterType((*GetBookViaAuthor)(nil), "example.GetBookViaAuthor")
	proto.RegisterType((*BookStore)(nil), "example.BookStore")
	proto.RegisterMapType((map[int64]string)(nil), "example.BookStore.BooksEntry")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xed, 0x24, 0xfd, 0xb0, 0x53, 0xd4, 0xb8, 0x88, 0xc6, 0x82, 0x50, 0x82, 0x87, 0xd0, 0x43,
	0x29, 0xed, 0xc1, 0x22, 0x78, 0xa8, 0x58, 0xa2, 0x08, 0x11, 0xd2, 0x56, 0xcf, 0xa9, 0x0c, 0x18,
	0xda, 0x66, 0x6b, 0xb2, 0x29, 0xf6, 0x4f, 0xf8, 0x93, 0x45, 0x76, 0xbb, 0xa6, 0x56, 0xbd, 0xf4,
	0x36, 0x6f, 0xf3, 0xde, 0x9b, 0xf7, 0x86, 0x20, 0x4e, 0x38, 0x9f, 0xb6, 0x16, 0x09, 0x17, 0x9c,
	0x55, 0xe8, 0x3d, 0x9c, 0x2f, 0x66, 0xe4, 0xdc, 0x61, 0xf1, 0x86, 0xf3, 0x29, 0x63, 0x58, 0x8c,
	0xd2, 0x49, 0x6c, 0x43, 0x03, 0x5c, 0x33, 0x50, 0x33, 0x3b, 0xc6, 0x92, 0x88, 0xc4, 0x8c, 0x6c,
	0xa3, 0x01, 0x6e, 0x35, 0x58, 0x03, 0x76, 0x82, 0xe5, 0x30, 0x13, 0xaf, 0x3c, 0xb1, 0x4d, 0xf5,
	0xac, 0x91, 0x73, 0x81, 0x07, 0x1e, 0x09, 0x69, 0x16, 0xd0, 0x5b, 0x46, 0xa9, 0xf8, 0xcf, 0xd3,
	0x69, 0xa2, 0xa5, 0x59, 0x4f, 0x51, 0xd8, 0x57, 0xca, 0x1f, 0x8e, 0xb0, 0xe5, 0xf8, 0x01, 0x58,
	0x95, 0xcc, 0xa1, 0xe0, 0x09, 0x49, 0xb7, 0x38, 0x9c, 0x93, 0xe6, 0xa8, 0x99, 0x75, 0xb1, 0x24,
	0x4b, 0xa5, 0xb6, 0xd1, 0x30, 0xdd, 0x5a, 0xe7, 0xbc, 0xa5, 0x6b, 0xb5, 0x72, 0x99, 0x9a, 0xd2,
	0x41, 0x2c, 0x92, 0x55, 0xb0, 0xe6, 0xd6, 0x7b, 0x88, 0x9b, 0x47, 0x66, 0xa1, 0x39, 0xa5, 0x95,
	0xce, 0x28, 0x47, 0x59, 0x7b, 0x19, 0xce, 0xb2, 0xbc, 0xb6, 0x02, 0x57, 0x46, 0x0f, 0x9a, 0x97,
	0x88, 0x83, 0x38, 0x9b, 0x0f, 0xd5, 0x0e, 0x56, 0xc3, 0xca, 0xd8, 0x7f, 0xf0, 0x1f, 0x9f, 0x7d,
	0xab, 0x20, 0xc1, 0x70, 0xd4, 0x0f, 0x46, 0x83, 0x5b, 0x0b, 0x24, 0x08, 0xc6, 0xbe, 0x7f, 0xef,
	0x7b, 0x16, 0xd4, 0x0d, 0x0b, 0x3a, 0x9f, 0x80, 0x35, 0x15, 0x89, 0x92, 0x65, 0xf4, 0x22, 0x73,
	0x57, 0xf4, 0x15, 0xd8, 0x69, 0x9e, 0x79, 0xfb, 0x7a, 0xf5, 0xfd, 0xad, 0x32, 0x4e, 0x81, 0xf5,
	0xf1, 0x48, 0x53, 0xd2, 0xcd, 0xed, 0xce, 0x7e, 0xcb, 0xf3, 0x4f, 0x7f, 0x0c, 0xda, 0xc0, 0xae,
	0xf1, 0xd0, 0x23, 0xe1, 0x25, 0x14, 0x0a, 0x4a, 0x77, 0xdc, 0xef, 0x02, 0xeb, 0xe1, 0xde, 0x77,
	0x82, 0x5d, 0x74, 0x6d, 0x98, 0x94, 0xd5, 0x6f, 0xd7, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xfc,
	0xd8, 0xba, 0x47, 0x84, 0x02, 0x00, 0x00,
}
